### ISSUE TITLE
Artifact removal, outlier detection and baseline wander removal 

### ISSUE THREAD

**Issue by hooman650** [rhenanbartels/hrv#16]
Hi,

Thanks for the hrv toolbox. I have noticed that there are numerous HRV toolboxes that perform the same function (computing time, frequency and nonlinearity parameters). But what I find missing in all of these are automated methods to remove outliers in RR intervals and also the baseline wandering. These substantially change the computed outcomes. I suggest looking into the page 11 of the document below for some ideas in this regard:
https://www.kubios.com/downloads/Kubios_HRV_Users_Guide.pdf

Also look into the paper below, how smoothness priors could be used to remove baseline wandering:
https://pdfs.semanticscholar.org/7b28/41f2b7013eccb3b75f72a1aada97ab66d551.pdf

These are relatively simple to implement but having these would make this toolbox definitely much more useful than the other very many ones that do the same operations.

Thanks
Hooman

**Comment by rhenanbartels** [comment]
Hi @hooman650, thank you very much for the suggestions.
I will work on them during the weekend.

Cheers!

**Comment by rhenanbartels** [comment]
Hi @hooman650, following your suggestions, I've implemented the following features regarding artifact removal and baseline trend removal:

#### Artifact removal
-  ```threshold_filter```: inspired in Kubios **threshold based artefact correction algorithm**, each RRi is compared to a local value consisting of the median of adjacent RRi. If the difference between RRi and the local median is greater than a given threshold in milliseconds this RRi is considered an ectopic beat. Ectopic RRi values are replaced with cubic spline interpolation of the entire tachogram.

It worth noticing that the previous version also offered 3 functions to remove artifacts:
 - moving average filter
 - moving median fitler
 - Quotient filter

#### Detrending functions
In order to remove simple slow or more complex trends, I've implemented 3 functions to remove low-frequency components from the RRi series:

  - ```polynomial_detrend```: fits a polynomial model of a given degree to the tachogram and remove it from each RRi values.
  - ```smoothness_priors```: widely used in hrv analyses, acts as a lowpass filter and remove complex trends from the RRi series
 - ```sg_detrend```: uses the savitzky-golay lowpass filter to remove low-frequency trends from the RRi series

With the detrend methods, I have also created an ```RRiDetrend``` class, which has the same behavior of base ```RRi``` class, but skip some validations of the RRi values, such as the tachogram can only have positive values.

Best regards,

Rhenan
