### ISSUE TITLE
Polar files

### ISSUE THREAD

**Issue by sambilbow** [rhenanbartels/hrv#24]
Hi, I saw on the docs that this takes .hrm polar files.

I have an H10 but haven't come across any way of getting the .hrm files from it yet, do you know how I can access them so I can provide your hrv tool the RRI?

Thanks

**Comment by rhenanbartels** [comment]
Hi @sambilbow, how are you doing? Sorry for the late reply, I am returning from vacations.

I've googled some specs about the H10 chest strap and found this answer from Polar support:

https://support.polar.com/en/support/how_long_a_training_session_can_i_record_with_h10
"**H10 records HR data once per second and ...**"

It says that the monitor record the Heart Rate every 1 second.

As far as I know, for an accurate Heart Rate Variability analysis, it is recommended to have the Heart-Rate recorded **Beat-by-Beat**, otherwise, Time and Frequency Domain methods won't be able to extract information about Heart-Rate fluctuations.

Despite that, probably there is a way to export the recorded data to a  **.txt** and/or **.csv** file, which the `hrv`module supports.

Let me know if I can help to analyse **.txt** or **.csv** files.

Cheers
